### ISSUE TITLE
Non-functional Requirements: Security

### ISSUE THREAD

**Issue by blairjam** [UCA-SoftwareEngineering/RoommateMatchingSystem#7]
What access shall be controlled, passwords, etc.

**Comment by sstone11** [comment]
I think Simplice already did this?

**Comment by brandonmitchell** [comment]
What the heck is this ?? Maybe wrong Brandon Mitchell ?

**Comment by blairjam** [comment]
@brandonmitchell Yeah, sorry for the confusion. We have a team member named brandonrmitchell. You just need to go to the top of the page and change your watch status to not watching or ignoring.

**Comment by blairjam** [comment]
@sstone11 Yes, he probably did. I'm just setting up the framework so we can all get on the same page of how to complete our Milestones and track our individual progress.

**Comment by brandonmitchell** [comment]
Nice . Ok . Well I am an engineer hehe .. But more on the system software side like SCCM and such .  Seems like a cool project

**Comment by blairjam** [comment]
Finished Milestone 2.
